2023-03-17 21:39:40,843 INFO    MainThread:511945 [wandb_setup.py:_flush():68] Configure stats pid to 511945
2023-03-17 21:39:40,843 INFO    MainThread:511945 [wandb_setup.py:_flush():68] Loading settings from /home/blackcerberus/.config/wandb/settings
2023-03-17 21:39:40,843 INFO    MainThread:511945 [wandb_setup.py:_flush():68] Loading settings from /home/blackcerberus/Documents/Documents/UNI/machine_learning/ML_project/ML-Group-51/wandb/settings
2023-03-17 21:39:40,843 INFO    MainThread:511945 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-03-17 21:39:40,843 INFO    MainThread:511945 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-03-17 21:39:40,844 INFO    MainThread:511945 [wandb_init.py:_log_setup():492] Logging user logs to /home/blackcerberus/Documents/Documents/UNI/machine_learning/ML_project/ML-Group-51/wandb/run-20230317_213940-mf0sgap8/logs/debug.log
2023-03-17 21:39:40,844 INFO    MainThread:511945 [wandb_init.py:_log_setup():493] Logging internal logs to /home/blackcerberus/Documents/Documents/UNI/machine_learning/ML_project/ML-Group-51/wandb/run-20230317_213940-mf0sgap8/logs/debug-internal.log
2023-03-17 21:39:40,844 INFO    MainThread:511945 [wandb_init.py:init():532] calling init triggers
2023-03-17 21:39:40,844 INFO    MainThread:511945 [wandb_init.py:init():538] wandb.init called with sweep_config: {}
config: {}
2023-03-17 21:39:40,844 INFO    MainThread:511945 [wandb_init.py:init():554] re-initializing run, found existing run on stack: dq8beqi7
2023-03-17 21:39:40,847 INFO    MainThread:511945 [wandb_run.py:_finish():1854] finishing run blackcerberus/fraud-detection/dq8beqi7
2023-03-17 21:39:40,848 INFO    MainThread:511945 [jupyter.py:save_history():449] not saving jupyter history
2023-03-17 21:39:40,848 INFO    MainThread:511945 [jupyter.py:save_ipynb():379] not saving jupyter notebook
2023-03-17 21:39:40,848 INFO    MainThread:511945 [wandb_init.py:_jupyter_teardown():420] cleaning up jupyter logic
2023-03-17 21:39:40,848 INFO    MainThread:511945 [wandb_run.py:_atexit_cleanup():2083] got exitcode: 0
2023-03-17 21:39:40,849 INFO    MainThread:511945 [wandb_run.py:_restore():2066] restore
2023-03-17 21:39:40,849 INFO    MainThread:511945 [wandb_run.py:_restore():2072] restore done
2023-03-17 21:39:45,317 INFO    MainThread:511945 [wandb_run.py:_footer_history_summary_info():3442] rendering history
2023-03-17 21:39:45,317 INFO    MainThread:511945 [wandb_run.py:_footer_history_summary_info():3474] rendering summary
2023-03-17 21:39:45,318 INFO    MainThread:511945 [wandb_run.py:_footer_sync_info():3398] logging synced files
2023-03-17 21:39:45,322 INFO    MainThread:511945 [wandb_init.py:init():588] starting backend
2023-03-17 21:39:45,322 INFO    MainThread:511945 [wandb_init.py:init():592] setting up manager
2023-03-17 21:39:45,324 INFO    MainThread:511945 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-03-17 21:39:45,324 INFO    MainThread:511945 [wandb_init.py:init():599] backend started and connected
2023-03-17 21:39:45,329 INFO    MainThread:511945 [wandb_run.py:_label_probe_notebook():1203] probe notebook
2023-03-17 21:39:45,329 INFO    MainThread:511945 [wandb_run.py:_label_probe_notebook():1213] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-03-17 21:39:45,329 INFO    MainThread:511945 [wandb_init.py:init():687] updated telemetry
2023-03-17 21:39:45,336 INFO    MainThread:511945 [wandb_init.py:init():727] communicating run to backend with 60.0 second timeout
2023-03-17 21:39:46,751 INFO    MainThread:511945 [wandb_run.py:_on_init():2134] communicating current version
2023-03-17 21:39:46,834 INFO    MainThread:511945 [wandb_run.py:_on_init():2143] got version response upgrade_message: "wandb version 0.14.0 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2023-03-17 21:39:46,834 INFO    MainThread:511945 [wandb_init.py:init():775] starting run threads in backend
2023-03-17 21:39:49,052 INFO    MainThread:511945 [wandb_run.py:_console_start():2114] atexit reg
2023-03-17 21:39:49,052 INFO    MainThread:511945 [wandb_run.py:_redirect():1969] redirect: SettingsConsole.WRAP_RAW
2023-03-17 21:39:49,052 INFO    MainThread:511945 [wandb_run.py:_redirect():2034] Wrapping output streams.
2023-03-17 21:39:49,052 INFO    MainThread:511945 [wandb_run.py:_redirect():2059] Redirects installed.
2023-03-17 21:39:49,052 INFO    MainThread:511945 [wandb_init.py:init():817] run started, returning control to user process
2023-03-17 21:39:49,053 INFO    MainThread:511945 [wandb_config.py:__setitem__():155] config set n_estimators = 100 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7fed2f1bbcd0>>
2023-03-17 21:39:49,053 INFO    MainThread:511945 [wandb_run.py:_config_callback():1250] config_cb n_estimators 100 None
2023-03-17 21:39:49,053 INFO    MainThread:511945 [wandb_config.py:__setitem__():155] config set random_state = 42 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7fed2f1bbcd0>>
2023-03-17 21:39:49,053 INFO    MainThread:511945 [wandb_run.py:_config_callback():1250] config_cb random_state 42 None
2023-03-17 21:51:33,434 INFO    MainThread:511945 [wandb_setup.py:_flush():68] Configure stats pid to 511945
2023-03-17 21:51:33,434 INFO    MainThread:511945 [wandb_setup.py:_flush():68] Loading settings from /home/blackcerberus/.config/wandb/settings
2023-03-17 21:51:33,434 INFO    MainThread:511945 [wandb_setup.py:_flush():68] Loading settings from /home/blackcerberus/Documents/Documents/UNI/machine_learning/ML_project/ML-Group-51/wandb/settings
2023-03-17 21:51:33,434 INFO    MainThread:511945 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-03-17 21:51:33,434 INFO    MainThread:511945 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-03-17 21:51:33,434 INFO    MainThread:511945 [wandb_init.py:_log_setup():492] Logging user logs to /home/blackcerberus/Documents/Documents/UNI/machine_learning/ML_project/ML-Group-51/wandb/run-20230317_215133-qxu3kxw6/logs/debug.log
2023-03-17 21:51:33,434 INFO    MainThread:511945 [wandb_init.py:_log_setup():493] Logging internal logs to /home/blackcerberus/Documents/Documents/UNI/machine_learning/ML_project/ML-Group-51/wandb/run-20230317_215133-qxu3kxw6/logs/debug-internal.log
2023-03-17 21:51:33,434 INFO    MainThread:511945 [wandb_init.py:_jupyter_setup():438] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fed2f1e78e0>
2023-03-17 21:51:33,435 INFO    MainThread:511945 [wandb_init.py:init():532] calling init triggers
2023-03-17 21:51:33,435 INFO    MainThread:511945 [wandb_init.py:init():538] wandb.init called with sweep_config: {}
config: {}
2023-03-17 21:51:33,435 INFO    MainThread:511945 [wandb_init.py:init():554] re-initializing run, found existing run on stack: mf0sgap8
2023-03-17 21:51:33,437 INFO    MainThread:511945 [wandb_run.py:_finish():1854] finishing run blackcerberus/fraud-detection/mf0sgap8
2023-03-17 21:51:33,437 INFO    MainThread:511945 [wandb_run.py:_atexit_cleanup():2083] got exitcode: 0
2023-03-17 21:51:33,437 INFO    MainThread:511945 [wandb_run.py:_restore():2066] restore
2023-03-17 21:51:33,437 INFO    MainThread:511945 [wandb_run.py:_restore():2072] restore done
2023-03-17 21:51:36,764 INFO    MainThread:511945 [wandb_run.py:_footer_history_summary_info():3442] rendering history
2023-03-17 21:51:36,764 INFO    MainThread:511945 [wandb_run.py:_footer_history_summary_info():3474] rendering summary
2023-03-17 21:51:36,766 INFO    MainThread:511945 [wandb_run.py:_footer_sync_info():3398] logging synced files
